spring:
  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/h2;AUTO_SERVER=TRUE
    username: db
    password: db1314
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
